# Heart Disease Prediction :
- Dataset link : [Heart Disease Cleveland UCI](https://www.kaggle.com/datasets/cherngs/heart-disease-cleveland-uci)

In [63]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

### Loading Dataset :

In [64]:
df = pd.read_csv('./heart.csv')

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [66]:
df.describe()

age          sex           cp     trestbps        chol   
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.00000  \
mean     54.434146     0.695610     0.942439   131.611707   246.00000   
std       9.072290     0.460373     1.029641    17.516718    51.59251   
min      29.000000     0.000000     0.000000    94.000000   126.00000   
25%      48.000000     0.000000     0.000000   120.000000   211.00000   
50%      56.000000     1.000000     1.000000   130.000000   240.00000   
75%      61.000000     1.000000     2.000000   140.000000   275.00000   
max      77.000000     1.000000     3.000000   200.000000   564.00000   

               fbs      restecg      thalach        exang      oldpeak   
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.000000  \
mean      0.149268     0.529756   149.114146     0.336585     1.071512   
std       0.356527     0.527878    23.005724     0.472772     1.175053   
min       0.000000     0.000000    71.000000     0.000000     0.000000   
25%       0.000000     0.000000   132.000000     0.000000     0.000000   
50%       0.000000     1.000000   152.000000     0.000000     0.800000   
75%       0.000000     1.000000   166.000000     1.000000     1.800000   
max       1.000000     2.000000   202.000000     1.000000     6.200000   

             slope           ca         thal       target  
count  1025.000000  1025.000000  1025.000000  1025.000000  
mean      1.385366     0.754146     2.323902     0.513171  
std       0.617755     1.030798     0.620660     0.500070  
min       0.000000     0.000000     0.000000     0.000000  
25%       1.000000     0.000000     2.000000     0.000000  
50%       1.000000     0.000000     2.000000     1.000000  
75%       2.000000     1.000000     3.000000     1.000000  
max       2.000000     4.000000     3.000000     1.000000

In [67]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope   
0   52    1   0       125   212    0        1      168      0      1.0      2  \
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [68]:
df.shape

(1025, 14)

### Preprocessing Data :

In [69]:
print(df.isnull().sum())

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64


In [70]:
df['target'].value_counts()

target
1    526
0    499
Name: count, dtype: int64

In [71]:
df.groupby('target').mean()

age       sex        cp    trestbps        chol       fbs   
target                                                                    
0       56.569138  0.827655  0.482966  134.106212  251.292585  0.164329  \
1       52.408745  0.570342  1.378327  129.245247  240.979087  0.134981   

         restecg     thalach     exang   oldpeak     slope        ca      thal  
target                                                                          
0       0.456914  139.130261  0.549098  1.600200  1.166333  1.158317  2.539078  
1       0.598859  158.585551  0.134981  0.569962  1.593156  0.370722  2.119772

1 --> Defective Heart

0 --> Healthy Heart

In [72]:
X = df.drop(columns = 'target', axis = 1)
Y = df['target']

In [73]:
print(X)

      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak   
0      52    1   0       125   212    0        1      168      0      1.0  \
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  
0         2   2     3  
1         0   0     3  
2  

In [74]:
print(Y)

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64


In [75]:
print(X.shape,Y.shape)

(1025, 13) (1025,)


In [76]:
X = np.array(X)
Y = np.array(Y)

In [77]:
# scaler = StandardScaler()

In [78]:
# scaler.fit(X)

In [79]:
# X = scaler.transform(X)

In [80]:
print(X)

[[52.  1.  0. ...  2.  2.  3.]
 [53.  1.  0. ...  0.  0.  3.]
 [70.  1.  0. ...  0.  0.  3.]
 ...
 [47.  1.  0. ...  1.  1.  2.]
 [50.  0.  0. ...  2.  0.  2.]
 [54.  1.  0. ...  1.  1.  3.]]


### Train-Test Split :

In [81]:
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.2, stratify=Y, random_state=2)

In [82]:
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape,type(x_train),type(y_train))

(820, 13) (820,) (205, 13) (205,) <class 'numpy.ndarray'> <class 'numpy.ndarray'>


### Model Training :

In [83]:
model = LogisticRegression(max_iter=10000)

In [84]:
model.fit(x_train,y_train)

LogisticRegression(max_iter=10000)

In [85]:
y_train_pred = model.predict(x_train)

In [86]:
accuracy_train = accuracy_score(y_train_pred,y_train)
print(accuracy_train)

0.8573170731707317


### Model Evaluation :

In [87]:
y_test_pred = model.predict(x_test)
accuracy_test = accuracy_score(y_test_pred,y_test)
print(f'Accuracy : {accuracy_test:.4f}')

Accuracy : 0.8049


### Predictive System :

In [88]:
sample_data = np.array([41,0,1,130,204,0,0,172,0,1.4,2,0,2])
sample_data = sample_data.reshape(1,-1)

In [89]:
y_pred = model.predict(sample_data)

In [90]:
if(y_pred[0]):
    print('The Person has Heart Disease')
else :
    print("The Person doesn't have Heart Disease")

The Person has Heart Disease


In [91]:
import pickle

In [92]:
data = {'model': model}

In [93]:
with open('model_heart.pkl','wb+') as file :
    pickle.dump(data,file)